spring.application.name=concurrency-safe-booking-system

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

server.port=${PORT:8080}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

llm.api.url=${LLM_API_URL:https://api.groq.com/openai/v1/chat/completions}
llm.api.key=${LLM_API_KEY}
llm.api.model=${LLM_API_MODEL:llama-3.3-70b-versatile}